//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("DB_9ACB12_jendouxDBModel", "FK__Query__UserProfi__25869641", "UserProfile", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(JendouxFree.Models.UserProfile), "Query", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(JendouxFree.Models.Query), true)]

#endregion

namespace JendouxFree.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DB_9ACB12_jendouxDBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DB_9ACB12_jendouxDBEntities object using the connection string found in the 'DB_9ACB12_jendouxDBEntities' section of the application configuration file.
        /// </summary>
        public DB_9ACB12_jendouxDBEntities() : base("name=DB_9ACB12_jendouxDBEntities", "DB_9ACB12_jendouxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_9ACB12_jendouxDBEntities object.
        /// </summary>
        public DB_9ACB12_jendouxDBEntities(string connectionString) : base(connectionString, "DB_9ACB12_jendouxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DB_9ACB12_jendouxDBEntities object.
        /// </summary>
        public DB_9ACB12_jendouxDBEntities(EntityConnection connection) : base(connection, "DB_9ACB12_jendouxDBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Query> Queries
        {
            get
            {
                if ((_Queries == null))
                {
                    _Queries = base.CreateObjectSet<Query>("Queries");
                }
                return _Queries;
            }
        }
        private ObjectSet<Query> _Queries;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<UserProfile> UserProfiles
        {
            get
            {
                if ((_UserProfiles == null))
                {
                    _UserProfiles = base.CreateObjectSet<UserProfile>("UserProfiles");
                }
                return _UserProfiles;
            }
        }
        private ObjectSet<UserProfile> _UserProfiles;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Queries EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToQueries(Query query)
        {
            base.AddObject("Queries", query);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the UserProfiles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUserProfiles(UserProfile userProfile)
        {
            base.AddObject("UserProfiles", userProfile);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_9ACB12_jendouxDBModel", Name="Query")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Query : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Query object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="url">Initial value of the Url property.</param>
        /// <param name="time">Initial value of the Time property.</param>
        /// <param name="userProfileId">Initial value of the UserProfileId property.</param>
        public static Query CreateQuery(global::System.Int32 id, global::System.String url, global::System.DateTime time, global::System.Int32 userProfileId)
        {
            Query query = new Query();
            query.Id = id;
            query.Url = url;
            query.Time = time;
            query.UserProfileId = userProfileId;
            return query;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Url
        {
            get
            {
                return _Url;
            }
            set
            {
                OnUrlChanging(value);
                ReportPropertyChanging("Url");
                _Url = StructuralObject.SetValidValue(value, false, "Url");
                ReportPropertyChanged("Url");
                OnUrlChanged();
            }
        }
        private global::System.String _Url;
        partial void OnUrlChanging(global::System.String value);
        partial void OnUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Time
        {
            get
            {
                return _Time;
            }
            set
            {
                OnTimeChanging(value);
                ReportPropertyChanging("Time");
                _Time = StructuralObject.SetValidValue(value, "Time");
                ReportPropertyChanged("Time");
                OnTimeChanged();
            }
        }
        private global::System.DateTime _Time;
        partial void OnTimeChanging(global::System.DateTime value);
        partial void OnTimeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 UserProfileId
        {
            get
            {
                return _UserProfileId;
            }
            set
            {
                OnUserProfileIdChanging(value);
                ReportPropertyChanging("UserProfileId");
                _UserProfileId = StructuralObject.SetValidValue(value, "UserProfileId");
                ReportPropertyChanged("UserProfileId");
                OnUserProfileIdChanged();
            }
        }
        private global::System.Int32 _UserProfileId;
        partial void OnUserProfileIdChanging(global::System.Int32 value);
        partial void OnUserProfileIdChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_9ACB12_jendouxDBModel", "FK__Query__UserProfi__25869641", "UserProfile")]
        public UserProfile UserProfile
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "UserProfile").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "UserProfile").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<UserProfile> UserProfileReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<UserProfile>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "UserProfile");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<UserProfile>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "UserProfile", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DB_9ACB12_jendouxDBModel", Name="UserProfile")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class UserProfile : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new UserProfile object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="createAt">Initial value of the CreateAt property.</param>
        /// <param name="visits">Initial value of the Visits property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="userAgent">Initial value of the UserAgent property.</param>
        /// <param name="mode">Initial value of the Mode property.</param>
        /// <param name="flashSpeed">Initial value of the FlashSpeed property.</param>
        /// <param name="slideSpeed">Initial value of the SlideSpeed property.</param>
        /// <param name="rollSpeed">Initial value of the RollSpeed property.</param>
        /// <param name="wordNum">Initial value of the WordNum property.</param>
        /// <param name="rowNum">Initial value of the RowNum property.</param>
        /// <param name="threshold">Initial value of the Threshold property.</param>
        /// <param name="fontSize">Initial value of the FontSize property.</param>
        /// <param name="font">Initial value of the Font property.</param>
        /// <param name="lineHeight">Initial value of the LineHeight property.</param>
        /// <param name="theme">Initial value of the Theme property.</param>
        /// <param name="highLight">Initial value of the HighLight property.</param>
        /// <param name="volume">Initial value of the Volume property.</param>
        public static UserProfile CreateUserProfile(global::System.Int32 id, global::System.DateTime createAt, global::System.Int32 visits, global::System.String location, global::System.String userAgent, global::System.String mode, global::System.String flashSpeed, global::System.String slideSpeed, global::System.String rollSpeed, global::System.String wordNum, global::System.String rowNum, global::System.String threshold, global::System.String fontSize, global::System.String font, global::System.String lineHeight, global::System.String theme, global::System.String highLight, global::System.String volume)
        {
            UserProfile userProfile = new UserProfile();
            userProfile.Id = id;
            userProfile.CreateAt = createAt;
            userProfile.Visits = visits;
            userProfile.Location = location;
            userProfile.UserAgent = userAgent;
            userProfile.Mode = mode;
            userProfile.FlashSpeed = flashSpeed;
            userProfile.SlideSpeed = slideSpeed;
            userProfile.RollSpeed = rollSpeed;
            userProfile.WordNum = wordNum;
            userProfile.RowNum = rowNum;
            userProfile.Threshold = threshold;
            userProfile.FontSize = fontSize;
            userProfile.Font = font;
            userProfile.LineHeight = lineHeight;
            userProfile.Theme = theme;
            userProfile.HighLight = highLight;
            userProfile.Volume = volume;
            return userProfile;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value, "Id");
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime CreateAt
        {
            get
            {
                return _CreateAt;
            }
            set
            {
                OnCreateAtChanging(value);
                ReportPropertyChanging("CreateAt");
                _CreateAt = StructuralObject.SetValidValue(value, "CreateAt");
                ReportPropertyChanged("CreateAt");
                OnCreateAtChanged();
            }
        }
        private global::System.DateTime _CreateAt;
        partial void OnCreateAtChanging(global::System.DateTime value);
        partial void OnCreateAtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Visits
        {
            get
            {
                return _Visits;
            }
            set
            {
                OnVisitsChanging(value);
                ReportPropertyChanging("Visits");
                _Visits = StructuralObject.SetValidValue(value, "Visits");
                ReportPropertyChanged("Visits");
                OnVisitsChanged();
            }
        }
        private global::System.Int32 _Visits;
        partial void OnVisitsChanging(global::System.Int32 value);
        partial void OnVisitsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false, "Location");
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserAgent
        {
            get
            {
                return _UserAgent;
            }
            set
            {
                OnUserAgentChanging(value);
                ReportPropertyChanging("UserAgent");
                _UserAgent = StructuralObject.SetValidValue(value, false, "UserAgent");
                ReportPropertyChanged("UserAgent");
                OnUserAgentChanged();
            }
        }
        private global::System.String _UserAgent;
        partial void OnUserAgentChanging(global::System.String value);
        partial void OnUserAgentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Mode
        {
            get
            {
                return _Mode;
            }
            set
            {
                OnModeChanging(value);
                ReportPropertyChanging("Mode");
                _Mode = StructuralObject.SetValidValue(value, false, "Mode");
                ReportPropertyChanged("Mode");
                OnModeChanged();
            }
        }
        private global::System.String _Mode;
        partial void OnModeChanging(global::System.String value);
        partial void OnModeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FlashSpeed
        {
            get
            {
                return _FlashSpeed;
            }
            set
            {
                OnFlashSpeedChanging(value);
                ReportPropertyChanging("FlashSpeed");
                _FlashSpeed = StructuralObject.SetValidValue(value, false, "FlashSpeed");
                ReportPropertyChanged("FlashSpeed");
                OnFlashSpeedChanged();
            }
        }
        private global::System.String _FlashSpeed;
        partial void OnFlashSpeedChanging(global::System.String value);
        partial void OnFlashSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String SlideSpeed
        {
            get
            {
                return _SlideSpeed;
            }
            set
            {
                OnSlideSpeedChanging(value);
                ReportPropertyChanging("SlideSpeed");
                _SlideSpeed = StructuralObject.SetValidValue(value, false, "SlideSpeed");
                ReportPropertyChanged("SlideSpeed");
                OnSlideSpeedChanged();
            }
        }
        private global::System.String _SlideSpeed;
        partial void OnSlideSpeedChanging(global::System.String value);
        partial void OnSlideSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RollSpeed
        {
            get
            {
                return _RollSpeed;
            }
            set
            {
                OnRollSpeedChanging(value);
                ReportPropertyChanging("RollSpeed");
                _RollSpeed = StructuralObject.SetValidValue(value, false, "RollSpeed");
                ReportPropertyChanged("RollSpeed");
                OnRollSpeedChanged();
            }
        }
        private global::System.String _RollSpeed;
        partial void OnRollSpeedChanging(global::System.String value);
        partial void OnRollSpeedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String WordNum
        {
            get
            {
                return _WordNum;
            }
            set
            {
                OnWordNumChanging(value);
                ReportPropertyChanging("WordNum");
                _WordNum = StructuralObject.SetValidValue(value, false, "WordNum");
                ReportPropertyChanged("WordNum");
                OnWordNumChanged();
            }
        }
        private global::System.String _WordNum;
        partial void OnWordNumChanging(global::System.String value);
        partial void OnWordNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String RowNum
        {
            get
            {
                return _RowNum;
            }
            set
            {
                OnRowNumChanging(value);
                ReportPropertyChanging("RowNum");
                _RowNum = StructuralObject.SetValidValue(value, false, "RowNum");
                ReportPropertyChanged("RowNum");
                OnRowNumChanged();
            }
        }
        private global::System.String _RowNum;
        partial void OnRowNumChanging(global::System.String value);
        partial void OnRowNumChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Threshold
        {
            get
            {
                return _Threshold;
            }
            set
            {
                OnThresholdChanging(value);
                ReportPropertyChanging("Threshold");
                _Threshold = StructuralObject.SetValidValue(value, false, "Threshold");
                ReportPropertyChanged("Threshold");
                OnThresholdChanged();
            }
        }
        private global::System.String _Threshold;
        partial void OnThresholdChanging(global::System.String value);
        partial void OnThresholdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FontSize
        {
            get
            {
                return _FontSize;
            }
            set
            {
                OnFontSizeChanging(value);
                ReportPropertyChanging("FontSize");
                _FontSize = StructuralObject.SetValidValue(value, false, "FontSize");
                ReportPropertyChanged("FontSize");
                OnFontSizeChanged();
            }
        }
        private global::System.String _FontSize;
        partial void OnFontSizeChanging(global::System.String value);
        partial void OnFontSizeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Font
        {
            get
            {
                return _Font;
            }
            set
            {
                OnFontChanging(value);
                ReportPropertyChanging("Font");
                _Font = StructuralObject.SetValidValue(value, false, "Font");
                ReportPropertyChanged("Font");
                OnFontChanged();
            }
        }
        private global::System.String _Font;
        partial void OnFontChanging(global::System.String value);
        partial void OnFontChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LineHeight
        {
            get
            {
                return _LineHeight;
            }
            set
            {
                OnLineHeightChanging(value);
                ReportPropertyChanging("LineHeight");
                _LineHeight = StructuralObject.SetValidValue(value, false, "LineHeight");
                ReportPropertyChanged("LineHeight");
                OnLineHeightChanged();
            }
        }
        private global::System.String _LineHeight;
        partial void OnLineHeightChanging(global::System.String value);
        partial void OnLineHeightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Theme
        {
            get
            {
                return _Theme;
            }
            set
            {
                OnThemeChanging(value);
                ReportPropertyChanging("Theme");
                _Theme = StructuralObject.SetValidValue(value, false, "Theme");
                ReportPropertyChanged("Theme");
                OnThemeChanged();
            }
        }
        private global::System.String _Theme;
        partial void OnThemeChanging(global::System.String value);
        partial void OnThemeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String HighLight
        {
            get
            {
                return _HighLight;
            }
            set
            {
                OnHighLightChanging(value);
                ReportPropertyChanging("HighLight");
                _HighLight = StructuralObject.SetValidValue(value, false, "HighLight");
                ReportPropertyChanged("HighLight");
                OnHighLightChanged();
            }
        }
        private global::System.String _HighLight;
        partial void OnHighLightChanging(global::System.String value);
        partial void OnHighLightChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Volume
        {
            get
            {
                return _Volume;
            }
            set
            {
                OnVolumeChanging(value);
                ReportPropertyChanging("Volume");
                _Volume = StructuralObject.SetValidValue(value, false, "Volume");
                ReportPropertyChanged("Volume");
                OnVolumeChanged();
            }
        }
        private global::System.String _Volume;
        partial void OnVolumeChanging(global::System.String value);
        partial void OnVolumeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DB_9ACB12_jendouxDBModel", "FK__Query__UserProfi__25869641", "Query")]
        public EntityCollection<Query> Queries
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Query>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "Query");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Query>("DB_9ACB12_jendouxDBModel.FK__Query__UserProfi__25869641", "Query", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
