//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class jQueryThemeNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal jQueryThemeNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.jQueryThemeNames", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to black tie.
        /// </summary>
        internal static string black_tie {
            get {
                return ResourceManager.GetString("black_tie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blitzer.
        /// </summary>
        internal static string blitzer {
            get {
                return ResourceManager.GetString("blitzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cupertino.
        /// </summary>
        internal static string cupertino {
            get {
                return ResourceManager.GetString("cupertino", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dark hive.
        /// </summary>
        internal static string dark_hive {
            get {
                return ResourceManager.GetString("dark_hive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dot luv.
        /// </summary>
        internal static string dot_luv {
            get {
                return ResourceManager.GetString("dot_luv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eggplant.
        /// </summary>
        internal static string eggplant {
            get {
                return ResourceManager.GetString("eggplant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to excite bike.
        /// </summary>
        internal static string excite_bike {
            get {
                return ResourceManager.GetString("excite_bike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flick.
        /// </summary>
        internal static string flick {
            get {
                return ResourceManager.GetString("flick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hot sneaks.
        /// </summary>
        internal static string hot_sneaks {
            get {
                return ResourceManager.GetString("hot_sneaks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to humanity.
        /// </summary>
        internal static string humanity {
            get {
                return ResourceManager.GetString("humanity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to le frog.
        /// </summary>
        internal static string le_frog {
            get {
                return ResourceManager.GetString("le_frog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mint choc.
        /// </summary>
        internal static string mint_choc {
            get {
                return ResourceManager.GetString("mint_choc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to overcast.
        /// </summary>
        internal static string overcast {
            get {
                return ResourceManager.GetString("overcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pepper grinder.
        /// </summary>
        internal static string pepper_grinder {
            get {
                return ResourceManager.GetString("pepper_grinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redmond.
        /// </summary>
        internal static string redmond {
            get {
                return ResourceManager.GetString("redmond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to smoothness.
        /// </summary>
        internal static string smoothness {
            get {
                return ResourceManager.GetString("smoothness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to south street.
        /// </summary>
        internal static string south_street {
            get {
                return ResourceManager.GetString("south_street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sunny.
        /// </summary>
        internal static string sunny {
            get {
                return ResourceManager.GetString("sunny", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to swanky purse.
        /// </summary>
        internal static string swanky_purse {
            get {
                return ResourceManager.GetString("swanky_purse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trontastic.
        /// </summary>
        internal static string trontastic {
            get {
                return ResourceManager.GetString("trontastic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui darkness.
        /// </summary>
        internal static string ui_darkness {
            get {
                return ResourceManager.GetString("ui_darkness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ui lightness.
        /// </summary>
        internal static string ui_lightness {
            get {
                return ResourceManager.GetString("ui_lightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vader.
        /// </summary>
        internal static string vader {
            get {
                return ResourceManager.GetString("vader", resourceCulture);
            }
        }
    }
}
