//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class JScriptVariables {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JScriptVariables() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.JScriptVariables", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jendoux.
        /// </summary>
        internal static string appName {
            get {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string CloseText {
            get {
                return ResourceManager.GetString("CloseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Url or Keywords here.
        /// </summary>
        internal static string DefaultUrlText {
            get {
                return ResourceManager.GetString("DefaultUrlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallel Reading.
        /// </summary>
        internal static string DocText {
            get {
                return ResourceManager.GetString("DocText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarge.
        /// </summary>
        internal static string EnlargeText {
            get {
                return ResourceManager.GetString("EnlargeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Player.
        /// </summary>
        internal static string FlashModeText {
            get {
                return ResourceManager.GetString("FlashModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string LastText {
            get {
                return ResourceManager.GetString("LastText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some Network Error Occurred. Please try later or report to administrator..
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string NextText {
            get {
                return ResourceManager.GetString("NextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play/Pause.
        /// </summary>
        internal static string PlayText {
            get {
                return ResourceManager.GetString("PlayText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crawl Player.
        /// </summary>
        internal static string RollModeText {
            get {
                return ResourceManager.GetString("RollModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  secs.
        /// </summary>
        internal static string SecondText {
            get {
                return ResourceManager.GetString("SecondText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the desired mode and start playing and watching.
        /// </summary>
        internal static string SelectModeText {
            get {
                return ResourceManager.GetString("SelectModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shrink.
        /// </summary>
        internal static string ShrinkText {
            get {
                return ResourceManager.GetString("ShrinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Climb Player.
        /// </summary>
        internal static string SlideModeText {
            get {
                return ResourceManager.GetString("SlideModeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string StopText {
            get {
                return ResourceManager.GetString("StopText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Mode.
        /// </summary>
        internal static string SwapText {
            get {
                return ResourceManager.GetString("SwapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  via app.jendoux.com.
        /// </summary>
        internal static string TDMsgAfter {
            get {
                return ResourceManager.GetString("TDMsgAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are Scroll Reading/Speed Reading .
        /// </summary>
        internal static string TDMsgBefore {
            get {
                return ResourceManager.GetString("TDMsgBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Player(s) formed:.
        /// </summary>
        internal static string TDNumText {
            get {
                return ResourceManager.GetString("TDNumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time to complete playing all text:.
        /// </summary>
        internal static string TDTimeText {
            get {
                return ResourceManager.GetString("TDTimeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Words in Players:.
        /// </summary>
        internal static string TDWordText {
            get {
                return ResourceManager.GetString("TDWordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string TipText {
            get {
                return ResourceManager.GetString("TipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  words.
        /// </summary>
        internal static string WordText {
            get {
                return ResourceManager.GetString("WordText", resourceCulture);
            }
        }
    }
}
