//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "11.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ShowTip {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowTip() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ShowTip", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Adjust Play Speed&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        1. &amp;lt;Use Setting Panel&amp;gt;
        ///        &lt;br /&gt;
        ///        Open Setting Panel &amp;#8594; Speed Tab
        ///        &lt;br /&gt;
        ///        Drag slider or Click Plus/Minus Button to get the desired value.
        ///        &lt;br /&gt;
        ///        &lt;br /&gt;
        ///
        ///        2. &amp;lt;Roll Mouse Wheel&amp;gt;
        ///        &lt;br /&gt;
        ///        Hover mouse on words/speed text strip, roll mouse wheel.
        ///        &lt;br /&gt;
        ///        Roll up to speed up; roll down to speed down.&lt;br /&gt;
        ///        &lt;small&gt;Note: Speed set by the mouse whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AdjustSpeed {
            get {
                return ResourceManager.GetString("AdjustSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Change Individual Player Mode&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        1. &amp;lt;Left-Click Player Mode Button&amp;gt;&lt;br /&gt;
        ///        The player will change from
        ///        &lt;br /&gt;
        ///        Flash Mode &amp;#8594; Slide Mode &amp;#8594; Text Mode
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        2. &amp;lt;Right-click Player Mode Button&amp;gt;&lt;br /&gt;
        ///        The player will change from
        ///        &lt;br /&gt;
        ///        Slide Mode &amp;#8594; Flash Mode &amp;#8594; Text Mode
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        3. &amp;lt;Middle-click text area&amp;gt;&lt;br /&gt;
        ///        The player will cycle throu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ChangeMode {
            get {
                return ResourceManager.GetString("ChangeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Speed Read Random Text&lt;/strong&gt;
        ///    &lt;p&gt;You may highlight text in a page and drag it to Drop Text button. A new text player will be created.&lt;/p&gt;
        ///    &lt;p&gt;Moreover, you may paste text copied from other souces to create players.&lt;/p&gt;
        ///    &lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/ye9ZhvpAnk4&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string DropText {
            get {
                return ResourceManager.GetString("DropText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Change Font in Text Player&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        Open Settings Panel &amp;#8594; Text Display Tab.&lt;br /&gt;
        ///        Choose desired font from Font Option. (Keyboard Shortcut: Ctrl+/)
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/UN6kyyGSjOs&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string Font {
            get {
                return ResourceManager.GetString("Font", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Change Font Size in Text Player&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        Open Settings Panel &amp;#8594; Text Display Tab. &lt;br /&gt;
        ///        Adjust Font Size to the desired value.&lt;/p&gt;&lt;p&gt;
        ///        Keyboard Shortcuts: &lt;br /&gt;Hold Ctrl, press - or = to decrease or increase.
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/AiDMOz9F00g&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string FontSize {
            get {
                return ResourceManager.GetString("FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Change Line Spacing in Text Player&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        Open Settings Panel &amp;#8594; Text Display Tab. &lt;br /&gt;
        ///        Adjust Line Spacing to the desired value.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Keyboard Shortcuts:
        ///        &lt;br /&gt;
        ///        Hold Alt, press - or = to decrease or increase.
        ///    &lt;/p&gt;
        ///    &lt;img src=&quot;Images/ShowTip/en/LineHeight.gif&quot; /&gt;.
        /// </summary>
        internal static string LineHeight {
            get {
                return ResourceManager.GetString("LineHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Advance/Rewind Text&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        1. &amp;lt;Click Last/Next Button&amp;gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///
        ///    &lt;p&gt;
        ///        2. &amp;lt;Roll Mouse Wheel&amp;gt;&lt;br /&gt;
        ///        Hover mouse on text area.
        ///        &lt;br /&gt;
        ///        Roll up or down mouse wheel to advance/rewind.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        3. &amp;lt;Press Right/Left Key&amp;gt;&lt;br /&gt;
        ///        Play the text first to notify the application which player to control.
        ///        &lt;br /&gt;
        ///        Press  &amp;#8592; / &amp;#8594; to rewind/advance
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; h [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Navigate {
            get {
                return ResourceManager.GetString("Navigate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Parallel Reading Pane&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        Click Parallel Reading Button to get the text pane.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        You can freely resize and reposition the pane.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Double click anywhere in the pane will close the pane
        ///    &lt;/p&gt;
        ///    &lt;img src=&quot;Images/ShowTip/en/ParallelReading.gif&quot; /&gt;.
        /// </summary>
        internal static string ParallelReading {
            get {
                return ResourceManager.GetString("ParallelReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Play/Pause&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        1. &amp;lt;Click Play/Pause Button&amp;gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        2. &amp;lt;Click on Text&amp;gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        3. &amp;lt;Press Space Key&amp;gt;&lt;br /&gt;
        ///        In order to notify the system the active player, the player has to be played once.
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/gs5Ho2rPZ4A&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string Play {
            get {
                return ResourceManager.GetString("Play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Adjust Player Size&lt;/strong&gt;
        ///    &lt;p&gt;
        ///      1. &amp;lt;Use Settings Panel&amp;gt;&lt;br /&gt;
        ///        Open Setting Panel &amp;#8594; Content Size. &lt;br /&gt;
        ///        Adjust Words/Line and Rows options to desired values.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        2. &amp;lt;Drag Resize Handle&amp;gt;&lt;br /&gt;
        ///        Hover Mouse on Resize Handler which is hidden in right bottom of the text.&lt;br /&gt;
        ///        Drag the handle until the text pane reaches desired size.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        3. &amp;lt;Use Keyboard Shortcuts&amp;gt;&lt;br /&gt;
        ///        Hold C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PlayerSize {
            get {
                return ResourceManager.GetString("PlayerSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Display Mode&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Left click&amp;gt;&lt;br /&gt;
        ///        Cycle through Flash Mode &amp;#8594; Slide Mode &amp;#8594; Document&lt;/p&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Right Click&amp;gt;&lt;br /&gt;
        ///        Reverse the cycle&lt;/p&gt;
        ///    &lt;img src=&quot;Images/ShowTip/en/MSB_Mode.gif&quot; /&gt;.
        /// </summary>
        internal static string PlayMode {
            get {
                return ResourceManager.GetString("PlayMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Query Textbox&lt;/strong&gt;
        ///    &lt;p&gt;This is how your speed read a webpage&lt;/p&gt;
        ///    &lt;p&gt;
        ///        Hold &lt;i&gt;Alt&lt;/i&gt; and Press &lt;i&gt;Q&lt;/i&gt; or &lt;i&gt;0&lt;/i&gt;, to move the cursor to this box.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        You may enter some key words you want to search or a hyperlink
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Then press enter key or click the search button on the right hand side.
        ///    &lt;/p&gt;
        ///    &lt;sub&gt;Keyboard shortcuts do not work when text cursor is in Query Textbox&lt;/sub&gt;
        ///    &lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string QueryTextBox {
            get {
                return ResourceManager.GetString("QueryTextBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Reset the player&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        1. &amp;lt;Click Stop Button&amp;gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        2. &amp;lt;Right-click on Text&amp;gt;&lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        3. &amp;lt;Press Backspace Key&amp;gt;&lt;br /&gt;
        ///        In order to notify the system the active player, the player has to be played once.
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/sy5lw8tXsoU&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Search Button&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Left click&amp;gt;&lt;br /&gt;
        ///        Take you to the destination page via Jendoux.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Middle click&amp;gt;&lt;br /&gt;
        ///        Open the destination page in a new tab.
        ///        &lt;small&gt;Pop Up function has to be enabled&lt;/small&gt;
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Right click&amp;gt;&lt;br /&gt;
        ///        Take you to the destination page directly
        ///    &lt;/p&gt;
        ///    &lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/VoZFYIMlnz8&quot; frameborder=&quot;0&quot; allowfulls [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SearchButton {
            get {
                return ResourceManager.GetString("SearchButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Change Theme Colours&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Theme&amp;gt;&lt;br /&gt;
        ///Open Setting Panel &amp;#8594; Environment Tab (keyboard shortcut: Alt + /) to select the desired Application Theme.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        &amp;lt;Highlight Colour&amp;gt;&lt;br /&gt;
        ///        Click colour palette button and choose the desired highlight colour.
        ///    &lt;/p&gt;
        ///&lt;iframe width=&quot;427&quot; height=&quot;240&quot; src=&quot;//www.youtube.com/embed/caYsZwXaYFE&quot; frameborder=&quot;0&quot; allowfullscreen&gt;&lt;/iframe&gt;.
        /// </summary>
        internal static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Filter out Short Paragraphs&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        You can filter out paragraphs with fewer text not to be playerised.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Open Settings Panel &amp;#8594; Content Size.&lt;br /&gt;
        ///        Adjust to desired value.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Keyboard Shortcuts: Hold Ctrl, Press Page Up or Page Down Key to increase or decrease.&lt;br /&gt;
        ///        This shortcut does not work in Chrome.
        ///        &lt;br /&gt;
        ///    &lt;/p&gt;
        ///    &lt;img src=&quot;Images/ShowTip/en/Threshold.gif&quot; /&gt;.
        /// </summary>
        internal static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;Adjust Volume of Sound Effects&lt;/strong&gt;
        ///    &lt;p&gt;
        ///        Open Settings Panel &amp;#8594; Environment Tab. &lt;br /&gt;
        ///        Adjust Volume to the desired value.
        ///    &lt;/p&gt;
        ///    &lt;p&gt;
        ///        Keyboard Shortcuts:
        ///        &lt;br /&gt;
        ///        Hold Ctrl, press Page Down or Page Up to decrease or increase.
        ///    &lt;/p&gt;
        ///    &lt;img src=&quot;Images/ShowTip/en/Volume.gif&quot; /&gt;.
        /// </summary>
        internal static string Volume {
            get {
                return ResourceManager.GetString("Volume", resourceCulture);
            }
        }
    }
}
